### PR TITLE
add azure environment configuration

### PR DESCRIPTION
**Pull request by Sneezry**

### CODE REVIEW

**Comment by chrmarti** [comment]
Thanks. We are waiting for some testing and downstream changes to support the other clouds.

**Comment by forester123** [comment]
Hi, what's the status of this? We have some docs of Azure China reply on this update.

**Comment by chrmarti** [comment]
We are working on enabling our app id for Azure China and we will need dependent extensions to update to support this before we can add the setting for real.

**Comment by ArthurMa1978** [comment]
@chrmarti can you give us a estimation of when will this pr be merged and new release within this change? We have been asked to support mooncake (China region) for long time from local customer.

**Comment by chrmarti** [comment]
Fixing with #83.

**Comment by chrmarti** [comment]
@ArthurMa1978 Should be early this week.

**Comment by ArthurMa1978** [comment]
cool, thanks @chrmarti !

**Pull request closed without merging**
